
analyzer:
  errors:
    deprecated_member_use: ignore
    deprecated_member_use_from_same_package: ignore
  exclude:
    - build/**
linter:
  rules:
    curly_braces_in_flow_control_structures: true
